let stockProductos = [
    {id: 1, nombre: "Buzo 1", tipo: "buzo", cantidad: 1, desc: "Buzos deportivos, ideales para tu entrenamiento", precio: 6500, talle: "XL", img: './img/buzo.jpg'},
    {id: 2, nombre: "Buzo 2", tipo: "buzo", cantidad: 1, desc: "Buzos deportivos, ideales para tu entrenamiento", precio: 6000, talle: "L", img: './img/buzo.jpg'},
    {id: 3, nombre: "Buzo 3", tipo: "buzo", cantidad: 1, desc: "Buzos deportivos, ideales para tu entrenamiento", precio: 5800, talle: "M", img: './img/buzo.jpg'},
    {id: 4, nombre: "Buzo 4", tipo: "buzo", cantidad: 1, desc: "Buzos deportivos, ideales para tu entrenamiento", precio: 5800, talle: "M", img: './img/buzo2.jpg'},
    {id: 5, nombre: "Buzo 5", tipo: "buzo", cantidad: 1, desc: "Buzos deportivos, ideales para tu entrenamiento", precio: 5500, talle: "S", img: './img/buzo.jpg'},
    {id: 6, nombre: "Buzo 6", tipo: "buzo", cantidad: 1, desc: "Buzos deportivos, ideales para tu entrenamiento", precio: 5500, talle: "S", img: './img/buzo2.jpg'},
    {id: 7, nombre: "Remera 1", tipo: "remera", cantidad: 1, desc: "Remeras para el gym, comodas e ideales para levantar pesas", precio: 4800, talle: "XL", img: './img/remera.jpg'},
    {id: 8, nombre: "Remera 2", tipo: "remera", cantidad: 1, desc: "Remeras para el gym, comodas e ideales para levantar pesas", precio: 4800, talle: "XL", img: './img/remeras2.jpg'},
    {id: 9, nombre: "Remera 3", tipo: "remera", cantidad: 1, desc: "Remeras para el gym, comodas e ideales para levantar pesas", precio: 4400, talle: "M", img: './img/remera.jpg'},
    {id: 10, nombre: "Remera 4", tipo: "remera", cantidad: 1, desc: "Remeras para el gym, comodas e ideales para levantar pesas", precio: 4400, talle: "M", img: './img/remeras2.jpg'},
    {id: 11, nombre: "Remera 5", tipo: "remera", cantidad: 1,desc: "Remeras para el gym, comodas e ideales para levantar pesas", precio: 4000, talle: "S", img: './img/remera.jpg'},
    {id: 12, nombre: "Remera 6", tipo: "remera", cantidad: 1, desc: "Remeras para el gym, comodas e ideales para levantar pesas", precio: 4000, talle: "S", img: './img/remeras2.jpg'},
    {id: 19, nombre: "Pantalon 1", tipo: "pantalon", cantidad: 1, desc: "Pantalones elastizados.", precio: 6200, talle: "L", img: './img/pantalon.jpg'},
    {id: 20, nombre: "Pantalon 2", tipo: "pantalon", cantidad: 1, desc: "Pantalones elastizados.", precio: 6200, talle: "L", img: './img/pantalon2.jpg'},
    {id: 21, nombre: "Pantalon 3", tipo: "pantalon", cantidad: 1, desc: "Pantalones elastizados.", precio: 5800, talle: "M", img: './img/pantalon.jpg'},
    {id: 22, nombre: "Pantalon 4", tipo: "pantalon", cantidad: 1, desc: "Pantalones elastizados.", precio: 5800, talle: "M", img: './img/pantalon2.jpg'},
    {id: 23, nombre: "Pantalon 5", tipo: "pantalon", cantidad: 1, desc: "Pantalones elastizados.", precio: 5500, talle: "S", img: './img/pantalon.jpg'},
    {id: 24, nombre: "Pantalon 6", tipo: "pantalon", cantidad: 1, desc: "Pantalones elastizados.", precio: 5500, talle: "S", img: './img/pantalon2.jpg'},
]